# master branch creates nightlies
-
  branches:
    only:
      - master
  version: '1.0.{build}'
  image: Visual Studio 2017 RC
  cache:
    - '%USERPROFILE%\.nuget\packages'
  platform: Any CPU
  configuration: Release
  environment:
    # Don't report back to the mothership
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  init:
    # Checking whether APPVEYOR_REPO_TAG_NAME is empty (thus falsy) is less clumsy than checking whether
    # APPVEYOR_REPO_TAG contains the string "true" or "false"
    # TODO: Since this should only trigger on master, there should never be a tag here, and we can just
    # default to the ci build number prefix to mark all packages a non-stable. Need to validate whether that's true
    - ps: $Env:LABEL = If ($Env:APPVEYOR_REPO_TAG_NAME) { "" } else {"CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")}
  before_build:
    - appveyor-retry dotnet restore "src\XSharpx\XSharpx.csproj"
  build_script:
    - dotnet msbuild "src\XSharpx\XSharpx.csproj" -property:c=%CONFIGURATION% -property:VersionSuffix=%LABEL%
  after_build:
    - dotnet msbuild "src\XSharpx\XSharpx.csproj" -target:pack -property:configuration=%CONFIGURATION% -property:VersionSuffix=%LABEL% -property:o=artifacts -verbosity:detailed
  artifacts:
    - path: .\**\.nupkg
  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

# This configuration is triggered on anything that isn't the branch "master"
# Note that tags are not "master", and tags are used to trigger a deploy
# That means that we have to build release packagages on this configuration
# Don't automatically publish them to the account and project feeds
# and deploy them iff it's a tag
-
  image: Visual Studio 2017 RC
  cache:
    - '%USERPROFILE%\.nuget\packages'
  platform: Any CPU
  configuration: Release
  environment:
    # Don't report back to the mothership
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  init:
    # Checking whether APPVEYOR_REPO_TAG_NAME is empty (thus falsy) is less clumsy than checking whether
    # APPVEYOR_REPO_TAG contains the string "true" or "false"
    - ps: $Env:LABEL = If ($Env:APPVEYOR_REPO_TAG_NAME) { "" } else {"CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")}
  before_build:
    - appveyor-retry dotnet restore "src\XSharpx\XSharpx.csproj"
  build_script:
    - dotnet msbuild "src\XSharpx\XSharpx.csproj" -property:c=%CONFIGURATION% -property:VersionSuffix=%LABEL%
  after_build:
    - dotnet msbuild "src\XSharpx\XSharpx.csproj" -target:pack -property:configuration=%CONFIGURATION% -property:VersionSuffix=%LABEL% -property:o=artifacts -verbosity:detailed
  artifacts:
    - path: .\**\.nupkg
    - type: NuGetPackage
  nuget:
    account_feed: false
    project_feed: false
  deploy:
    provider: NuGet
    api_key:
      secure: foo
    skip_symbols: false
    on:
      appveyor_repo_tag: true