# master branch creates nightlies
-
  branches:
    only:
      - master
  version: '1.0.{build}'
  image: Visual Studio 2017 RC
  cache:
    - '%USERPROFILE%\.nuget\packages'
  platform: Any CPU
  configuration: Release
  environment:
    # Don't report back to the mothership
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  init:
    - ps: $Env:LABEL = If ($Env:APPVEYOR_REPO_TAG_NAME) { "" } else {"CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")}
  before_build:
    - appveyor-retry dotnet restore "src\XSharpx\XSharpx.csproj"
  build_script:
    - dotnet msbuild "src\XSharpx\XSharpx.csproj" -property:c=%CONFIGURATION% -property:VersionSuffix=%LABEL%
  after_build:
    - dotnet msbuild "src\XSharpx\XSharpx.csproj" -target:pack -property:configuration=%CONFIGURATION% -property:VersionSuffix=%LABEL% -property:o=artifacts -verbosity:detailed
  artifacts:
    - path: .\**\.nupkg

# "fall back" configuration for all other branches/tags
# no "branches" section defined
# deploy on tag
-
  version: '1.0.{build}'
  image: Visual Studio 2017 RC
  cache:
    - '%USERPROFILE%\.nuget\packages'
  platform: Any CPU
  configuration: Release
  environment:
    # Don't report back to the mothership
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  init:
    - ps: $Env:LABEL = If ($Env:APPVEYOR_REPO_TAG_NAME) { "" } else {"CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")}
  before_build:
    - appveyor-retry dotnet restore "src\XSharpx\XSharpx.csproj"
  build_script:
    - dotnet msbuild "src\XSharpx\XSharpx.csproj" -property:c=%CONFIGURATION% -property:VersionSuffix=%LABEL%
  artifacts:
    - path: .\**\.nupkg
  deploy:
    provider: NuGet
    api_key:
      secure: foo
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true